### ISSUE TITLE
scripts/mkregs.py: input using dictionary and no parse

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-lib#240]
Motivation (Problem)

-- every time I need to add or modify a register, I forget the meaning of the fields

Side Benefit

--without parse, the code will be much simpler

Objective

change 

IOB_SWREG_W(TXSOFT_RST,         1,  0, -1, 0, 1)     //Soft reset.

to 

{'Name': 'TXSOFT_RST', 'Type': 'W', 'Width': 1, 'ResetValue', Address: -1, 'AdressWidth': 0, 'AutoLogic': 1}

So, I know the fields I am writing all the time, even if I have to copy one of the existent

Use a .json file 

Place an example mkregs.json in iob-lib's root

Priority: HIGH

**Comment by jjts** [comment]
Also good, but can we put the fields in the same line separated by commas?

**Comment by P-Miranda** [comment]
It is possible, for example, with `mkregs.toml`:
```toml
[[latex_tab1]]
# Using inline tables
RUN = { type = "W", nbits = "1", reset_value = 0, address = -1, address_w = 0, autologic = true }

[[latex_tab1]]
DONE = { type = "R", nbits = "1", reset_value = 0, address = -1, address_w = 0, autologic = true }

[[latex_tab2]]
TX_DATA = { type = "W", nbits = "8", reset_value = 0, address = -1, address_w = 0, autologic = true }
```
and a parsing script like this:
```python
#!/usr/bin/env python

import tomli
import sys

if __name__ == "__main__":
    with open("mkregs.toml", "rb") as f:
        toml_dict = tomli.load(f)

    print(toml_dict)
    for table, regs in toml_dict.items():
        print(f"\nTable: {table}")
        for reg in regs:
            (reg_name, reg_fields), = reg.items()
            print(f'\tName: {reg_name} | Fields: {reg_fields}')
```
we get the following output`(using inline tables gives a slightly diferent data structure):
```
{'latex_tab1': [{'RUN': {'type': 'W', 'nbits': '1', 'reset_value': 0, 'address': -1, 'address_w': 0, 'autologic': True}}, {'DONE': {'type': 'R', 'nbits': '1', 'reset_value': 0, 'address': -1, 'address_w': 0, 'autologic': True}}], 'latex_tab2': [{'TX_DATA': {'type': 'W', 'nbits': '8', 'reset_value': 0, 'address': -1, 'address_w': 0, 'autologic': True}}]}

Table: latex_tab1
        Name: RUN | Fields: {'type': 'W', 'nbits': '1', 'reset_value': 0, 'address': -1, 'address_w': 0, 'autologic': True}
        Name: DONE | Fields: {'type': 'R', 'nbits': '1', 'reset_value': 0, 'address': -1, 'address_w': 0, 'autologic': True}

Table: latex_tab2
        Name: TX_DATA | Fields: {'type': 'W', 'nbits': '8', 'reset_value': 0, 'address': -1, 'address_w': 0, 'autologic': True}
```
